version: '3.8'

services:
  app:
    build: .
    command:
      [ "sh", "-c", "npx sequelize-cli db:migrate --config ./config/config.json --env local && npx sequelize-cli db:seed:all --config ./config/config.json --env local && npm start" ]

    env_file:
      - ./env/.env.local
    container_name: taa-esg-service
    ports:
      - "8082:8082"
    working_dir: /var/www
    restart: unless-stopped
    volumes:
      - ./:/var/www
      - /var/www/node_modules
    depends_on:
      - postgres
    networks:
      - postgres


  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
      - ./init-db-local.sql:/docker-entrypoint-initdb.d/init.sql  
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped


networks:
  postgres:
    driver: bridge 

volumes:
  postgres:
  pgadmin:
