version: '3.8'

services:
  app:
    build: .
    command:
      [ "sh", "-c", "npx sequelize-cli db:migrate --config ./config/config.json --env development && npm start" ]

    env_file:
      - ./env/.env.development
    container_name: taa-esg-service-dev
    ports:
      - "8082:8082"
    working_dir: /var/www
    restart: unless-stopped
    volumes:
      - ./:/var/www
      - /var/www/node_modules
    depends_on:
      - postgres
    networks:
      - postgres


  postgres:
    container_name: postgres_container_dev
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
      - postgres_dev:/data/postgres
      - ./init-db-local.sql:/docker-entrypoint-initdb.d/init.sql  
    networks:
      - postgres
    restart: unless-stopped



networks:
  postgres:
    driver: bridge 

volumes:
  postgres_dev: