name: Deploy Backend

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: root
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            mkdir -p /var/www/esg/ESG_Backend
            cd /var/www/esg/ESG_Backend
            if [ ! -d .git ]; then
              git clone -b develop https://github.com/hamzafallahi/ESG_Backend.git .
            else
              git fetch origin develop
              git reset --hard origin/develop
            fi
            docker compose down || true
            docker compose up -d --build
